### ISSUE TITLE
Consider using k8s cli-runtime modules 

### ISSUE THREAD

**Issue by rflorenc** [bakito/kubexporter#13]
Hi @bakito,

This tool is really helpful, thanks making it available! :man_mechanic:
I'm still going through the code but I thought I'd leave some suggestions for convenience modules to use and to make kubexporter more kubectl plugin friendly. Sorry if I'm missing something!

Namely packages `https://godoc.org/k8s.io/cli-runtime/pkg/genericclioptions` and `https://godoc.org/k8s.io/cli-runtime/pkg/printers` might be interesting to add, as they already provide kubectl compatible output options, like -n/--namespace or -o/--output json/yaml, --jsonpath, support for go-template functions, etc. 

These are both from `https://github.com/kubernetes/cli-runtime`.

**Comment by bakito** [comment]
Hi @rflorenc 

Thank your for opening this issue.
I'l have a look ant it an consider extending/adapting it.

as for in #14 I already switched to use the standard libraries to get the kubeconfig.
