### ISSUE TITLE
segfault on intel mac

### ISSUE THREAD

**Issue by sstarcher** [bakito/kubexporter#344]
bash-3.2$ kubexporter
Segmentation fault: 11

Darwin ShaneStarcher 22.6.0 Darwin Kernel Version 22.6.0: Fri Sep 15 13:39:52 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_X86_64 x86_64 i386 Darwin

Ran from https://github.com/bakito/kubexporter/releases/download/v0.5.2/kubexporter_0.5.2_darwin_amd64.tar.gz

**Comment by sstarcher** [comment]
I built from source and it works fine

**Comment by bakito** [comment]
@sstarcher the reason for this could be that the binary is compressed with https://github.com/upx/upx
I'll make a new, uncompressed release.

**Comment by bakito** [comment]
can you check with https://github.com/bakito/kubexporter/releases/tag/v0.5.3 ?

**Comment by sstarcher** [comment]
That version works for me
